name: test-nodejs
on:
  push:
    branches:
      - master

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] # Adjust the Node.js version as needed

    steps:
      - name: Checking out latest code
        uses: actions/checkout@v3


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm start

      - run: pwd
      - run: ls -la

      - name: Deploy files to server
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          #localDir: "dist"
          remoteDir: "/var/www/node-test/"
          # args: "-o ConnectTimeout=5"
